spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000


logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace
